"""Generate additive MySQL 8 development initialization from repository SQL and mall DOs.
Existing tables are left untouched. Generated SQL is validated in a scratch database before use.
"""
from pathlib import Path
import re, json
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'sql/mysql/local-init'
EXISTING=set((ROOT/'outputs/db-init/existing-tables.txt').read_text(encoding='utf-8-sig').splitlines())
notes=[]

def strip_comments(s):
    return re.sub(r'/\*.*?\*/|--[^\n]*', '', s, flags=re.S)

def split_sql(s, separator=';'):
    parts=[]; start=0; quote=None; depth=0; i=0
    while i<len(s):
        c=s[i]
        if quote:
            if c=='\\': i+=2; continue
            if c==quote:
                if i+1<len(s) and s[i+1]==quote: i+=2; continue
                quote=None
        elif c in "'\"`": quote=c
        elif c=='(': depth+=1
        elif c==')': depth-=1
        elif c==separator and (separator==';' or depth==0):
            parts.append(s[start:i].strip()); start=i+1
        i+=1
    if s[start:].strip(): parts.append(s[start:].strip())
    return parts

def normalize(s):
    s=re.sub(r'"([\w]+)"',r'`\1`',s)
    s=re.sub(r'GENERATED BY DEFAULT AS IDENTITY(?:\([^)]*\))?', 'AUTO_INCREMENT', s,flags=re.I)
    s=re.sub(r'\b(?:long|number)\b', 'bigint',s,flags=re.I)
    s=re.sub(r'\bclob\b','LONGTEXT',s,flags=re.I)
    s=re.sub(r'\bvarchar\b(?!\s*\()', 'varchar(255)',s,flags=re.I)
    s=re.sub(r'varchar\((\d+)\)',lambda m:'LONGTEXT' if int(m[1])>4000 else m[0],s,flags=re.I)
    # H2 accepts defaults on long text directly; MySQL 8 needs expression defaults.
    s=re.sub(r"(LONGTEXT[^,\n]*?DEFAULT)\s+('(?:[^']|'')*')",r'\1 (\2)',s,flags=re.I)
    return s

tables={}; indexes=[]; alterations=[]; sources=[]
files=sorted(ROOT.glob('nomix-module-*/**/src/test/resources/sql/create_tables.sql'))
files += [ROOT/'sql/mysql/quartz.sql']
for file in files:
    relative=file.relative_to(ROOT).as_posix(); sources.append(relative)
    source=strip_comments(file.read_text(encoding='utf-8-sig'))
    # The upstream product test file contains DROP TABLE ... (columns): an invalid CREATE typo.
    source,n=re.subn(r'DROP TABLE IF EXISTS\s+`product_comment`\s*\(', 'CREATE TABLE IF NOT EXISTS `product_comment` (', source,flags=re.I)
    if n: notes.append('Corrected malformed product_comment CREATE statement in '+relative)
    for statement in split_sql(source):
        s=normalize(statement)
        m=re.match(r'CREATE TABLE(?: IF NOT EXISTS)?\s+`?(\w+)`?\s*\(',s,re.I)
        if m:
            table=m[1]; opening=s.index('(',m.start()); depth=1; quote=None; closing=None
            for i in range(opening+1,len(s)):
                c=s[i]
                if quote:
                    if c==quote and s[i-1]!='\\': quote=None
                elif c in "'`": quote=c
                elif c=='(':depth+=1
                elif c==')':
                    depth-=1
                    if depth==0: closing=i;break
            if closing is None: raise ValueError('Unbalanced CREATE '+table)
            tables[table]={'parts':split_sql(s[opening+1:closing],','),'source':relative,'tail':s[closing+1:].strip()}
        elif re.match(r'CREATE (?:UNIQUE )?INDEX',s,re.I): indexes.append(s)
        elif re.match(r'ALTER TABLE',s,re.I): alterations.append(s)
        elif re.match(r'INSERT INTO',s,re.I) and file.name=='quartz.sql': notes.append('Skipped historical Quartz scheduler data: '+s[:65])
        elif re.match(r'(?:SET |DROP TABLE|BEGIN|COMMIT)',s,re.I): pass
        else: raise ValueError('Unclassified statement '+s[:150])
for s in alterations:
    m=re.match(r'ALTER TABLE `?(\w+)`?\s+ADD IF NOT EXISTS\s+(.+)',s,re.S|re.I)
    if not m:raise ValueError('Unsupported ALTER '+s)
    tables[m[1]]['parts'].append(m[2])
for s in indexes:
    m=re.match(r'CREATE (UNIQUE )?INDEX IF NOT EXISTS `?(\w+)`?\s+ON `?(\w+)`?\s*(\(.*)',s,re.S|re.I)
    if not m:raise ValueError('Unsupported index '+s)
    tables[m[3]]['parts'].append(('UNIQUE ' if m[1] else '')+'KEY `'+m[2]+'` '+m[4])

# Current mall/member/pay models supply tables/fields absent from older H2 tests.
def snake(s):return re.sub(r'(?<!^)(?=[A-Z])','_',s).lower()
def sqltype(t,name,annotation):
    if name=='id':return 'bigint NOT NULL AUTO_INCREMENT'
    if t in ('Long','long'):return 'bigint DEFAULT NULL'
    if t in ('Integer','int','Short','short','Byte','byte'):return 'int DEFAULT NULL'
    if t in ('Boolean','boolean'):return 'bit(1) DEFAULT NULL'
    if t in ('LocalDateTime','Date'):return 'datetime DEFAULT NULL'
    if t=='LocalDate':return 'date DEFAULT NULL'
    if t=='LocalTime':return 'time DEFAULT NULL'
    if t=='BigDecimal':return 'decimal(24,6) DEFAULT NULL'
    if t in ('Double','double','Float','float'):return 'double DEFAULT NULL'
    if t=='String':
        large=('typeHandler' in annotation or any(k in name.lower() for k in ('property','content','description','remark','reason','config','url','json','notify','response','request')))
        return ('LONGTEXT' if large else 'varchar(512)')+' DEFAULT NULL'
    if t.startswith(('List<','Set<','Map<')) or t.endswith('[]') or 'typeHandler' in annotation:return 'LONGTEXT DEFAULT NULL'
    raise ValueError('Unknown Java field type '+t+' '+name)

model_tables={}
for module in ('nomix-module-mall','nomix-module-member','nomix-module-pay'):
 for file in (ROOT/module).rglob('*DO.java'):
    if '/src/main/java/' not in file.as_posix() or '/dal/dataobject/' not in file.as_posix():continue
    raw=file.read_text(encoding='utf-8-sig')
    s=re.sub(r'/\*.*?\*/|//[^\n]*','',raw,flags=re.S)
    tm=re.search(r'@TableName\(\s*(?:value\s*=\s*)?"([^"]+)"',s)
    if not tm:continue
    name=tm[1]; cm=re.search(r'public class \w+[^\{]*\{',s)
    if not cm:raise ValueError('No class '+str(file))
    body=s[cm.end():]; fields={}; previous=0
    for fm in re.finditer(r'private\s+([\w<>,?\[\] ]+?)\s+(\w+)\s*(?:=[^;]*)?;',body):
        prefix=body[:fm.start()]
        if prefix.count('{')!=prefix.count('}'):continue
        typ=fm[1].strip(); field=fm[2]
        if 'static' in typ:continue
        annotation=body[previous:fm.start()]; previous=fm.end()
        if re.search(r'@TableField\([^)]*exist\s*=\s*false',annotation,re.S):continue
        explicit=re.search(r'@TableField\(\s*(?:value\s*=\s*)?"([^"]+)"',annotation)
        column=explicit[1] if explicit else snake(field)
        fields[column]=(typ,annotation)
    if 'id' not in fields:raise ValueError('No id '+name)
    existing=tables.get(name,{}); old={}
    for part in existing.get('parts',[]):
        match=re.match(r'`(\w+)`\s+',part)
        if match:old[match[1]]=part
    parts=[]
    for column,(typ,annotation) in fields.items():
        # Preserve explicit tested scalar lengths/defaults where the Java type still agrees.
        definition=old.get(column)
        inferred=sqltype(typ,column,annotation)
        if definition and typ=='String' and 'LONGTEXT' not in inferred and re.match(r'`\w+`\s+varchar',definition,re.I):parts.append(definition)
        elif definition and typ in ('Integer','Long','Boolean','BigDecimal') and re.match(r'`\w+`\s+(bigint|int|tinyint|bit|boolean|decimal)\b',definition,re.I):parts.append(definition)
        else:parts.append('`'+column+'` '+inferred)
    if re.search(r'extends\s+(?:TenantBaseDO|BaseDO)',s):
        parts += ["`creator` varchar(64) DEFAULT ''",'`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP',"`updater` varchar(64) DEFAULT ''",'`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP','`deleted` bit(1) NOT NULL DEFAULT 0']
    if 'tenant_id' not in fields:parts.append('`tenant_id` bigint NOT NULL DEFAULT 0')
    parts.append('PRIMARY KEY (`id`)')
    parts.append('KEY `idx_tenant_id` (`tenant_id`)')
    tables[name]={'parts':parts,'source':file.relative_to(ROOT).as_posix(),'tail':''}
    model_tables[name]={'source':file.relative_to(ROOT).as_posix(),'fields':list(fields),'had_test_ddl':bool(existing),'added_fields':sorted(set(fields)-set(old))}

statements=[]; created=[]; skipped=[]
for table,info in sorted(tables.items()):
    if table in EXISTING:skipped.append(table);continue
    # Standard charset and row format. Original Quartz foreign keys remain intact.
    statement='-- Source: '+info['source']+'\nCREATE TABLE IF NOT EXISTS `'+table+'` (\n  '+',\n  '.join(info['parts'])+'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;'
    statements.append(statement);created.append(table)
OUT.mkdir(parents=True,exist_ok=True)
header='-- Local development schema, generated from this checkout. Existing tables are not altered.\nSET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n'
(OUT/'01-schema.sql').write_text(header+'\n\n'.join(statements)+'\nSET FOREIGN_KEY_CHECKS=1;\n',encoding='utf-8')
report={'sources':sources,'new_tables':created,'existing_tables_skipped':skipped,'mall_model_alignment':model_tables,'notes':notes,'limitations':['Non-mall modules are converted test schemas, not a production completeness guarantee.','Inferred new field lengths/nullability/indexes need business validation before production.','No cleanup scripts, DROP, TRUNCATE, or vendor-specific duplicate initialization executed.']}
(OUT/'manifest.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'source_files':len(sources),'new_tables':len(created),'existing_skipped':len(skipped),'mall_models':len(model_tables),'notes':notes},ensure_ascii=False))

